# Generated by Django 5.1.1 on 2024-09-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='work_location_prefecture',
            field=models.CharField(default='東京都', max_length=255),
        ),
    ]
