# Generated by Django 5.1.1 on 2024-09-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_joblisting_work_location_prefecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='work_location_prefecture',
        ),
    ]
