# Generated by Django 5.1.1 on 2024-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_joblisting_work_location_prefecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='job_id',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='average_age',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='average_annual_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='average_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='block',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='building',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='capital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='corporation_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='cp_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='current_earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='current_earnings_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='establishment_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='facebook_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='female_manager_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='female_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='handicapped_employee_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='industry_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='logo_img_url_pc',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='logo_img_url_sp',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='name_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='name_kana',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='paid_holiday_digestibility',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='postal_code',
            field=models.CharField(default='0000000', max_length=7),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='pr_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='prefecture',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='president_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='president_position',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='sales_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='stock_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='town',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='turnover_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='twitter_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='web_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='y_company_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='local_government_code',
            field=models.IntegerField(default=0),
        ),
    ]
