# Generated by Django 5.1.1 on 2024-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_joblisting_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='average_age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
