# Generated by Django 5.1.1 on 2024-09-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_joblisting_average_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='logo_img_url_pc',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='logo_img_url_sp',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='average_annual_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='average_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='capital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='corporation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='cp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='current_earnings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='current_earnings_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='female_manager_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='female_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='handicapped_employee_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='industry_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='listed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='local_government_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='name_kana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='paid_holiday_digestibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='pr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='prefecture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='president_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='president_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='sales_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='stock_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='turnover_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='y_company_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
