# Generated by Django 5.1.1 on 2024-09-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_joblisting_logo_img_url_pc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='establishment_date',
        ),
    ]
