# Generated by Django 5.1.1 on 2024-09-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_joblisting_establishment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='current_earnings_date',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='sales_date',
        ),
    ]
